name: 'Setup Conan'
description: 'Install Conan package manager'
inputs:
  profile:
    description: 'Used profile'
    required: true
  shell:
    description: 'Used shell for executing commands'
    required: false
    default: ${{ runner.os == 'Linux' && 'bash' || 'pwsh' }}
  cache:
    description: 'Use cache'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Conan
      shell: ${{ inputs.shell }}
      run: pipx install conan
    - name: Echo installed version
      shell: ${{ inputs.shell }}
      run: |
        conan --version
        echo "version=$(conan --version)" >> $GITHUB_OUTPUT

    - name: Install Conan configuration files
      shell: ${{ inputs.shell }}
      run: |
        conan config install conan/global.conf

    - name: Set environment variables
      if: ${{ runner.os == 'Linux' }}
      shell: ${{ inputs.shell }}
      run: |
          echo "CONAN_CACHE_LOCATION=$(conan config home)" >> $GITHUB_ENV

    - name: Set environment variables
      if: ${{ runner.os == 'Windows' }}
      shell: ${{ inputs.shell }}
      run: |
        echo "CONAN_CACHE_LOCATION=$(conan config home)" >> $env:GITHUB_ENV

    - name: Cache Conan packages
      id: cache-conan-packages
      if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: ${{ env.CONAN_CACHE_LOCATION }}/p
        key: ${{ inputs.profile }}-${{ hashFiles('conanfile.py') }}
        
    - name: Detect default profile
      shell: ${{ inputs.shell }}
      run: |
        conan profile detect --force

    - name: Build all dependencies
      shell: ${{ inputs.shell }}
      run: |
        conan install . --build=missing --profile=ci/conan/${{ inputs.profile }}

    - name: Cleanup temporary folders from cache
      shell: ${{ inputs.shell }}
      run: |
        conan cache clean --temp --source
