name: 'Setup Conan'
inputs:
  compiler:
    description: 'Used compiler'
    required: true
  compiler-version:
    description: 'Used compiler version'
    required: true
  arch:
    description: 'Target architecture'
    required: false
    default: 'x64'
  profile:
    description: 'Used profile'
    required: true
  shell:
    description: 'Used shell for executing commands'
    required: false
    default: ${{ runner.os == 'Linux' && 'bash' || 'pwsh' }}

runs:
  using: 'composite'
  steps:
    - name: Install Conan
      if: ${{ runner.os == 'Linux' }}
      shell: ${{ inputs.shell }}
      run: pipx install conan
    - name: Install Conan
      if: ${{ runner.os == 'Windows' }}
      shell: ${{ inputs.shell }}
      run: pip3 install conan
    - name: Echo installed version
      shell: ${{ inputs.shell }}
      run: |
        conan --version
        echo "version=$(conan --version)" >> $GITHUB_OUTPUT

    - name: Install Conan configuration files
      shell: ${{ inputs.shell }}
      run: |
        conan config install conan/global.conf

    - name: Set environment variables
      if: ${{ runner.os == 'Linux' }}
      shell: ${{ inputs.shell }}
      run: |
          echo "CONAN_CACHE_LOCATION=$(conan config home)" >> $GITHUB_ENV
          echo "COMPILER_NAME=${{ inputs.compiler }}" >> $GITHUB_ENV
          echo "COMPILER_VER=${{ inputs.compiler-version }}" >> $GITHUB_ENV

    - name: Set environment variables
      if: ${{ runner.os == 'Windows' }}
      shell: ${{ inputs.shell }}
      run: |
        echo "CONAN_CACHE_LOCATION=$(conan config home)" >> $env:GITHUB_ENV

    - name: Cache Conan packages
      id: cache-conan-packages
      uses: actions/cache@v4
      with:
        path: ${{ env.CONAN_CACHE_LOCATION }}/p
        key: ${{ inputs.compiler }}-${{ inputs.profile }}-${{ hashFiles('conanfile.py') }}
        
    - name: Detect default profile
      shell: ${{ inputs.shell }}
      run: |
        conan profile detect --force

    - name: Build all dependencies
      shell: ${{ inputs.shell }}
      run: |
        conan install . --build=missing --profile=ci/conan/${{ inputs.profile }}
