version: 2.1

workflows:
  version: 2
  GCC:
    jobs:
      - build_with_gcc:
          context:
            - docker-hub-creds
  Clang:
    jobs:
      - build_with_clang:
          context:
            - docker-hub-creds

jobs:
  build_with_gcc:
    docker:
      - image: 'jankelemen/cpp-starter-template-buildenv:latest'
        auth:
          username: jankelemen
          password: $DOCKERHUB_PASSWORD
    environment:
      CC: gcc-10
      CXX: g++-10
    steps:
      - checkout
      - run: ./ci/circle.sh
  build_with_clang:
    docker:
      - image: 'jankelemen/cpp-starter-template-buildenv:latest'
        auth:
          username: jankelemen
          password: $DOCKERHUB_PASSWORD
    environment:
      CC: clang-11
      CXX: clang++-11
    steps:
      - checkout
      - run: ./ci/circle.sh

