version: 2.1
jobs:
  build:
    docker:
      - image: 'jankelemen/cpp-starter-template-buildenv:latest'
        auth:
          username: jankelemen
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: g++-10

