version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds
jobs:
  build:
    docker:
      - image: 'jankelemen/cpp-starter-template-buildenv:latest'
        auth:
          username: jankelemen
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo $DOCKERHUB_LOGIN

