FROM jankelemen/cpp-build-environment:0.1.0

LABEL maintainer="Jan Kelemen" \
      description="Build environment for cpp-starter-template" \
      version="0.2.0"

ARG DEBIAN_FRONTEND=noninteractive

