name: aarch64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-22.04
    
    env:
      GCC_VER: 12
      CLANG_VER: 17
      
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]
        
    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v4

      - name: Install gcc-${{ env.GCC_VER }}
        if:  matrix.compiler == 'gcc'
        run: |
          sudo apt-get install -y gcc-${{ env.GCC_VER }}-aarch64-linux-gnu g++-${{ env.GCC_VER }}-aarch64-linux-gnu

          echo "CONAN_PROFILE=aarch64-gcc-${{ env.GCC_VER }}" >> $GITHUB_ENV

      - name: Install clang-${{ env.CLANG_VER }}
        if: matrix.compiler == 'clang'
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          . /etc/lsb-release
          sudo add-apt-repository -y "deb http://apt.llvm.org/${DISTRIB_CODENAME}/ llvm-toolchain-${DISTRIB_CODENAME}-${{ env.CLANG_VER }} main"
          sudo apt-get install -y clang-${{ env.CLANG_VER }} llvm-${{ env.CLANG_VER }}

          echo "CONAN_PROFILE=clang-${{ env.CLANG_VER }}" >> $GITHUB_ENV
              
      - name: Install Conan
        uses: turtlebrowser/get-conan@v1.2
        with:
          version: 2.0.17

      - name: Fetch dependencies
        run: |
          conan profile detect --force
          conan install . --profile=conan/${{ env.CONAN_PROFILE }} --build=* --settings build_type=Release

      - name: Configure CMake
        run: |
          cmake --preset release

      - name: Build
        run: |
          cmake --build --preset=release

