name: CI

# Run the action on each push to master branch and pull requests against master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allow running manually from actions tab
  workflow_dispatch:

# Jobs of the workflow
jobs:
  build-gcc: # Build configuration with GCC compiler
    runs-on: ubuntu-18.04
    name: GCC build
    steps:
      - uses: actions/checkout@v2 # Check out repository under $GITHUB_WORKSPACE
      - uses: turtlebrowser/get-conan@v1.0 # Install conan

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build-clang: # Build configuration with Clang compiler
    runs-on: ubuntu-18.04
    name: Clang build
    steps:
      - uses: actions/checkout@v2 # Check out repository under $GITHUB_WORKSPACE
      - uses: turtlebrowser/get-conan@v1.0 # Install conan

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
